version: 2

models:
  - name: enrollments
    tests:
      - dbt_utils.expression_is_true:
          expression: "LEFT(batch_id, 2) = 'BT'"
      - dbt_utils.expression_is_true:
              expression: "LEFT(course_id, 2) = 'CR'"
    columns:
      - name: enrollment_id
        tests:
          - unique
          - not_null
      - name: student_id
        tests:
          - not_null
      - name: course_id
        tests:
          - not_null
      - name: batch_id
        tests:
          - not_null
  - name: students
    tests:
      - dbt_utils.expression_is_true:
          expression: "LEFT(student_id, 2) = 'ST'"
      - dbt_utils.expression_is_true:
          expression: "LEFT(school_id, 2) = 'SC'"
          