version: 2

models:
  - name: quiz_messages_deserialize
    columns:
      - name: flow_name
        tests:
          - not_null
          - accepted_values:
              values: ['Template quiz flow question - 5']