version: 2

models:
  - name: student_enrollments
    columns:
      - name: enrollment_id
        tests:
          - unique
          - not_null
      - name: student_id
        tests:
          - not_null
      - name: course_id
        tests:
          - not_null
      - name: batch_id
        tests:
          - not_null
      - name: student_name
        tests:
          - not_null
  - name: enrollment_messages
    tests: 
      - duplicate_messages
    columns:
      - name: message_id
        tests:
          - not_null
      - name: activity_status
        tests:
          - not_null
          - accepted_values:
              values: ['Activity_Sent', 'Activity_Access', 'Activity_Submission']
      - name: enrollment_id
        tests:
          - not_null
      - name: student_id
        tests:
          - not_null
      - name: course_id
        tests:
          - not_null
      - name: batch_id
        tests:
          - not_null
      - name: student_name
        tests:
          - not_null