sources:
    - name: crm
      description: Tables here have the data from TAP crm (postgres) collected by the ops team
      schema: dalgo_staging
      tables:
          - name: tabStudent
            identifier: tabStudent
            description: Student details
          - name: tabCourse
            identifier: tabCourse
            description: Course details
          - name: tabBatch
            identifier: tabBatch
            description: Batch details
          - name: tabSchool
            identifier: tabSchool
            description: School details
          - name: tabEnrollment
            identifier: tabEnrollment
            description: Enrollment details
