sources:
    - name: crm
      description: Tables here have the data from TAP crm (postgres) collected by the ops team
      schema: testing_glific_tap
      tables:
          - name: tabStudent
            identifier: tabStudent
            description: Student details
