sources:
    - name: glific
      description: Tables here have the TAP glific bigquery data
      schema: "918454812392"
      tables:
          - name: messages
            identifier: messages
            description: This has the raw messages data from the TAP buddy
